spring:
  main:
    allow-bean-definition-overriding: true
notion:
  version: [NOTION_VERSION]
  api_token: [NOTION_API_TOKEN]
github:
  api_token: [GITHUB_API_TOKEN]
  client_id: [GITHUB_CLIENT_ID]
  client_secret: [GITHUB_CLIENT_SECRET]
  redirect_url: http://[DOMAIN]/api/github/callback